title: Wasi Naqvi
show_downloads: false
logo: /assets/headshot.jpg
theme: jekyll-theme-minimal




# Footer Information
footer:
  copyright: Â© 2024 Wasi Naqvi. All rights reserved.
  powered_by: Powered by Jekyll and GitHub Pages

# Other Settings
permalink: pretty
markdown: kramdown
timezone: America/New_York
