title: Wasi Naqvi
description: "Exoplanets, hierarchical Bayesian modelling, and instrumentation."
show_downloads: false
logo: /assets/IMG-20251017-WA0078.jpg

theme: jekyll-theme-minimal

header_pages:
  - index.md

# Footer Information
footer:
  copyright: Â© 2024 Wasi Naqvi. All rights reserved.
  powered_by: Powered by Jekyll and GitHub Pages

# Other Settings
permalink: pretty
markdown: kramdown
timezone: America/New_York

# Custom CSS
include:
  - assets/styles.css
